# Generated by Django 5.0.1 on 2025-11-07 19:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofCartIdentityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid_id', models.CharField(editable=False, help_text='Format: PID-XXXXXX', max_length=20, unique=True)),
                ('wallet_address', models.CharField(help_text="Seller's blockchain wallet address", max_length=255)),
                ('nft_token_address', models.CharField(blank=True, help_text='On-chain NFT token address', max_length=255, null=True)),
                ('blockchain_network', models.CharField(choices=[('solana-devnet', 'Solana Devnet'), ('solana-mainnet', 'Solana Mainnet'), ('icp-testnet', 'ICP Testnet'), ('icp-mainnet', 'ICP Mainnet')], default='solana-devnet', max_length=20)),
                ('mint_transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash for PID mint', max_length=255, null=True)),
                ('kyc_hash', models.CharField(help_text='Reference to KYC hash', max_length=64)),
                ('metadata_uri', models.URLField(blank=True, help_text='IPFS or on-chain metadata URI', null=True)),
                ('status', models.CharField(choices=[('MINTING', 'Minting in Progress'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='MINTING', max_length=20)),
                ('reputation_score', models.IntegerField(default=100, help_text='Reputation score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('blacklist_flag', models.BooleanField(default=False, help_text='If true, seller is blacklisted for fraud')),
                ('blacklist_reason', models.TextField(blank=True, null=True)),
                ('blacklist_date', models.DateTimeField(blank=True, null=True)),
                ('minted_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Never for PID tokens (soulbound)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proofcart_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProofCart Identity Token',
                'verbose_name_plural': 'ProofCart Identity Tokens',
                'db_table': 'proofcart_identity_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bond_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Bond amount in USDC/test tokens', max_digits=10)),
                ('currency', models.CharField(default='USDC', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Deposit'), ('HELD', 'Held in Escrow'), ('RELEASED', 'Released to Seller'), ('SLASHED', 'Slashed for Fraud'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('escrow_address', models.CharField(blank=True, help_text='Smart contract escrow address', max_length=255, null=True)),
                ('deposit_transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('release_transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('slashed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('slash_reason', models.TextField(blank=True, null=True)),
                ('slashed_at', models.DateTimeField(blank=True, null=True)),
                ('deposited_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pid_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bond', to='sellers.proofcartidentitytoken')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_bond', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Bond',
                'verbose_name_plural': 'Seller Bonds',
                'db_table': 'seller_bonds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_legal_name', models.CharField(help_text='Full name as per ID', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Kenya', max_length=100)),
                ('national_id_number', models.CharField(max_length=50, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('phone_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=64, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual Seller'), ('SOLE_PROPRIETOR', 'Sole Proprietorship'), ('PARTNERSHIP', 'Partnership'), ('LIMITED_COMPANY', 'Limited Company'), ('CORPORATION', 'Corporation')], default='INDIVIDUAL', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('id_document_front', models.FileField(help_text='National ID or Passport - Front', upload_to='kyc/id_documents/')),
                ('id_document_back', models.FileField(blank=True, help_text='National ID - Back (if applicable)', null=True, upload_to='kyc/id_documents/')),
                ('selfie_photo', models.ImageField(help_text='Selfie holding ID for verification', upload_to='kyc/selfies/')),
                ('business_certificate', models.FileField(blank=True, help_text='Business registration certificate (if applicable)', null=True, upload_to='kyc/business_docs/')),
                ('kyc_hash', models.CharField(editable=False, help_text='SHA256 hash of verified KYC data', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_kyc', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this KYC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller KYC',
                'verbose_name_plural': 'Seller KYC Records',
                'db_table': 'seller_kyc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='proofcartidentitytoken',
            name='kyc_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_token', to='sellers.sellerkyc'),
        ),
        migrations.CreateModel(
            name='SellerReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('SUCCESSFUL_SALE', 'Successful Sale'), ('POSITIVE_REVIEW', 'Positive Review'), ('NEGATIVE_REVIEW', 'Negative Review'), ('DISPUTE_OPENED', 'Dispute Opened'), ('DISPUTE_LOST', 'Dispute Lost'), ('FRAUD_CONFIRMED', 'Fraud Confirmed'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=30)),
                ('event_description', models.TextField()),
                ('score_before', models.IntegerField()),
                ('score_change', models.IntegerField(help_text='Can be positive or negative')),
                ('score_after', models.IntegerField()),
                ('order_id', models.UUIDField(blank=True, help_text='Related order UUID', null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_adjustments', to=settings.AUTH_USER_MODEL)),
                ('pid_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_logs', to='sellers.proofcartidentitytoken')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Reputation Log',
                'verbose_name_plural': 'Seller Reputation Logs',
                'db_table': 'seller_reputation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
