# Generated by Django 5.0.1 on 2025-11-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('metadata_uri', models.URLField()),
                ('icp_transaction_hash', models.CharField(max_length=255)),
                ('current_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=True)),
                ('mint_date', models.DateTimeField(auto_now_add=True)),
                ('ownership_history', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nft', to='products.product')),
            ],
            options={
                'db_table': 'nfts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFTMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.JSONField(default=dict)),
                ('warranty_info', models.TextField(blank=True)),
                ('certification', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('documents', models.JSONField(default=list)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('manufacturing_location', models.CharField(blank=True, max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_metadata', to='nft.nft')),
            ],
            options={
                'db_table': 'nft_metadata',
            },
        ),
        migrations.AddIndex(
            model_name='nft',
            index=models.Index(fields=['nft_id'], name='nfts_nft_id_ac9538_idx'),
        ),
        migrations.AddIndex(
            model_name='nft',
            index=models.Index(fields=['serial_number'], name='nfts_serial__6996fb_idx'),
        ),
    ]
