# Generated by Django 5.0.1 on 2025-11-07 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_qr_code_url_product_qr_environment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('escrow_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_address', models.TextField()),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(default='IntaSend', max_length=50)),
                ('intasend_payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('intasend_payment_link', models.URLField(blank=True, max_length=500, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('blockchain_escrow_tx_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('blockchain_release_tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('escrow_created_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_released_at', models.DateTimeField(blank=True, null=True)),
                ('intasend_payout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payout_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_RECEIVED', 'Payment Received'), ('FUNDS_IN_ESCROW', 'Funds in Escrow'), ('IN_TRANSIT', 'In Transit'), ('PENDING_RELEASE', 'Pending Release Confirmation'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='PAYMENT_PENDING', max_length=30)),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_scan_serial', models.CharField(blank=True, max_length=255, null=True)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('dispute_opened_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(default='Solana', max_length=20)),
                ('escrow_address', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_tx_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('release_tx_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('buyer_wallet', models.CharField(max_length=255)),
                ('seller_wallet', models.CharField(max_length=255)),
                ('amount_held', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('HELD', 'Held'), ('RELEASED', 'Released'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('smart_contract_data', models.JSONField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='payments.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED_BUYER', 'Resolved - Buyer Favor'), ('RESOLVED_SELLER', 'Resolved - Seller Favor'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_case', to='payments.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('PAYOUT', 'Payout'), ('REFUND', 'Refund')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('intasend_transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('intasend_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at', 'buyer'], name='payments_or_created_c6b2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at', 'seller'], name='payments_or_created_b0f9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='payments_or_status_5bb726_idx'),
        ),
    ]
