# Generated by Django 5.0.1 on 2025-11-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='Full verification URL encoded in QR code', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_environment',
            field=models.CharField(blank=True, choices=[('development', 'Development'), ('production', 'Production')], help_text='Environment for which QR was generated', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, help_text='When QR code was last generated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_image_filename',
            field=models.CharField(blank=True, help_text='QR code image filename', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('result', models.CharField(choices=[('verified', 'Verified - Product Found'), ('not_found', 'Not Found - Invalid Serial'), ('error', 'Error - Verification Failed')], help_text='Scan verification result', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, help_text='Product if found', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='products.product')),
            ],
            options={
                'db_table': 'scan_logs',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['serial_number', '-scanned_at'], name='scan_logs_serial__567bdb_idx'), models.Index(fields=['result', '-scanned_at'], name='scan_logs_result_248d30_idx')],
            },
        ),
    ]
