# Generated by Django 5.0.1 on 2025-11-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_qr_code_url_product_qr_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid_reference',
            field=models.CharField(blank=True, help_text='ProofCart Identity Token ID of the seller (e.g., PID-000023)', max_length=20, null=True),
        ),
    ]
